server:
  port: 9090
spring:
  datasource:
    name: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot?characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
    druid:
      initial-size: 50
      min-idle: 50
      max-active: 100
      max-wait: 30000
      query-timeout: 10
      remove-abandoned: true
      remove-abandoned-timeout: 180
      log-abandoned: true
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=6000

mysql-lock:
  tableName: opt_lock
  expireSeconds: 70


# mybatis配置
mybatis:
  mapperLocations: classpath:mapper/**/*.xml